// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftArchVehicleFleetManager.Data;

#nullable disable

namespace SoftArchVehicleFleetManager.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    [Migration("20251125215046_PasswordHash introduced")]
    partial class PasswordHashintroduced
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("SoftArchVehicleFleetManager.Models.Alarm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlarmJSON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FleetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InterfaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.HasIndex("InterfaceId");

                    b.ToTable("Alarms");
                });

            modelBuilder.Entity("SoftArchVehicleFleetManager.Models.Fleet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fleets");
                });

            modelBuilder.Entity("SoftArchVehicleFleetManager.Models.Interface", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterfaceJSON")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Interfaces");
                });

            modelBuilder.Entity("SoftArchVehicleFleetManager.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("SoftArchVehicleFleetManager.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HardwareId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InterfaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InterfaceId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("SoftArchVehicleFleetManager.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FleetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SoftArchVehicleFleetManager.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FleetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SoftArchVehicleFleetManager.Models.Alarm", b =>
                {
                    b.HasOne("SoftArchVehicleFleetManager.Models.Fleet", "Fleet")
                        .WithMany("Alarms")
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoftArchVehicleFleetManager.Models.Interface", "Interface")
                        .WithMany()
                        .HasForeignKey("InterfaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fleet");

                    b.Navigation("Interface");
                });

            modelBuilder.Entity("SoftArchVehicleFleetManager.Models.Interface", b =>
                {
                    b.HasOne("SoftArchVehicleFleetManager.Models.Manufacturer", "Manufacturer")
                        .WithMany("Interfaces")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("SoftArchVehicleFleetManager.Models.Module", b =>
                {
                    b.HasOne("SoftArchVehicleFleetManager.Models.Interface", "Interface")
                        .WithMany()
                        .HasForeignKey("InterfaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftArchVehicleFleetManager.Models.Manufacturer", "Manufacturer")
                        .WithMany("Modules")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoftArchVehicleFleetManager.Models.Vehicle", "Vehicle")
                        .WithMany("Modules")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Interface");

                    b.Navigation("Manufacturer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SoftArchVehicleFleetManager.Models.User", b =>
                {
                    b.HasOne("SoftArchVehicleFleetManager.Models.Fleet", "Fleet")
                        .WithMany()
                        .HasForeignKey("FleetId");

                    b.HasOne("SoftArchVehicleFleetManager.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Fleet");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("SoftArchVehicleFleetManager.Models.Vehicle", b =>
                {
                    b.HasOne("SoftArchVehicleFleetManager.Models.Fleet", "Fleet")
                        .WithMany("Vehicles")
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("SoftArchVehicleFleetManager.Models.Fleet", b =>
                {
                    b.Navigation("Alarms");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SoftArchVehicleFleetManager.Models.Manufacturer", b =>
                {
                    b.Navigation("Interfaces");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("SoftArchVehicleFleetManager.Models.Vehicle", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
